on:
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-18.04
    name: Build Admin Production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build ADmin
        run: |
          docker build --no-cache -t quintessential.azurecr.io/conduit-admin:${{ env.RELEASE_VERSION }} .
          docker push quintessential.azurecr.io/conduit-admin:${{ env.RELEASE_VERSION }}
