name: Test application build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20"
      - run: yarn
      - run: CI=false npx lerna run build
